default: &default
  adapter:  mysql2
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: root                       # - actually, U dont need to use root user to connect to DB
  # password: nasta1807                  # - rails will use logged in system user by default
  # socket: /var/run/mysqld/mysqld.sock  # - perform `whoami` to see that username
                                         # - then open `mysql -uroot`
                                         # - and run the code below:
                                         # - CREATE USER 'YOUR_USER_NAME'@'localhost';
                                         # - GRANT ALL PRIVILEGES ON *.* TO 'YOUR_USER_NAME'@'localhost' WITH GRANT OPTION;

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  database: chat_test

production:
  <<: *default
  database: chat_production
  username: chat
  password: <%= ENV['CHAT_DATABASE_PASSWORD'] %>
